stages:
  - Build
  - Backup
  - Deploy


Build VueJS:
  stage: Build
  tags:
    - macos
    - windows
    - linux
  script:
    - npm install
    - npm run electron:build
  artifacts:
    paths:
      - dist_electron/
  except:
    - schedules